"""Evidence export service (T010) — derive the §14.2 evidence report from RunLog.

Design constraints:
  - build_evidence_report is PURE: no clocks, no UUIDs, no I/O inside.
    The router generates report_id + timestamp and passes them in.
  - Separation invariant: FeedbackEvents appear ONLY under human_review;
    simulator_facts NEVER contains a feedback value.
  - Conditional sections (final_parameters, final_hyperparameters,
    expert_override_events, run_comparison_reference) are omitted when
    not applicable.
  - Pre-M5 runs with no driver/vehicle/speed profiles export them as null
    (no error; the RunLog fields default to None).
  - The report is a derived view — it is NOT persisted.
  - The report MUST NOT claim the simulator independently judged the algorithm.

§14.2 report shape:
  { report_id, run_id, timestamp, ui_language, simulator_version,
    package: {id, version}, scenario: {id, version},
    simulator_facts: {
      route_snapshot, route_facts, event_plan, run_mode, evidence_status,
      initial_parameters, final_parameters?, initial_hyperparameters,
      final_hyperparameters?, driver_profile, vehicle_profile,
      timeline_events, decision_trace, proposal_events, actions,
      expert_override_events?, algorithm_errors, run_comparison_reference? },
    human_review: { feedback_labels, free_text_comments } }
"""

from __future__ import annotations

from typing import Any

from aica_api.models.log import RunLog


def build_evidence_report(
    run_log: RunLog,
    *,
    report_id: str,
    timestamp: str,
    ui_language: str = "bilingual",
) -> dict[str, Any]:
    """Derive the §14.2 evidence report from a persisted RunLog.

    Args:
        run_log:     The RunLog to derive the report from.
        report_id:   Opaque report identifier (generated by the router at the
                     request boundary — NOT generated inside this function).
        timestamp:   ISO-8601 timestamp of the export (generated by the router).
        ui_language: The UI language selected by the reviewer when triggering
                     the export (e.g. ``"ja"``, ``"en"``).  Defaults to
                     ``"bilingual"`` for back-compat with pre-M6 callers.

    Returns:
        A plain dict matching the §14.2 evidence report shape.  No feedback
        value appears inside ``simulator_facts``.
    """
    # ── Partition events by kind ───────────────────────────────────────────────
    tick_events = []
    action_events = []
    algorithm_errors = []
    feedback_events = []

    for event in run_log.events:
        kind = event.kind
        if kind == "tick":
            tick_events.append(event)
        elif kind == "action":
            action_events.append(event)
        elif kind == "algorithm_error":
            algorithm_errors.append(event)
        elif kind == "feedback":
            feedback_events.append(event)
        # Unknown kinds are silently ignored (forward-compat)

    # ── simulator_facts derivations ────────────────────────────────────────────

    # timeline_events = all NON-feedback events in their recorded order
    timeline_events = [
        e.model_dump(mode="json")
        for e in run_log.events
        if e.kind != "feedback"
    ]

    # decision_trace = {tick_index, decision_result} for every TickEvent
    decision_trace = [
        {
            "tick_index": e.tick_index,
            "decision_result": e.trace.decision_result.model_dump(mode="json"),
        }
        for e in tick_events
    ]

    # proposal_events = TickEvents where fire_control.fired=True AND proposal is not None
    proposal_events = [
        e.model_dump(mode="json")
        for e in tick_events
        if e.trace.decision_result.fire_control.fired
        and e.trace.decision_result.proposal is not None
    ]

    actions = [e.model_dump(mode="json") for e in action_events]

    alg_errors = [e.model_dump(mode="json") for e in algorithm_errors]

    # ── Conditional parameters / hyperparameters ───────────────────────────────
    simulator_facts: dict[str, Any] = {
        "route_snapshot": run_log.display_route.model_dump(mode="json") if run_log.display_route else None,
        "route_facts": run_log.route_facts.model_dump(mode="json"),
        "event_plan": run_log.event_plan.model_dump(mode="json"),
        "run_mode": run_log.run_mode,
        "evidence_status": run_log.evidence_status,
        "initial_parameters": run_log.initial_parameters,
        "initial_hyperparameters": run_log.initial_hyperparameters,
        # Pre-M5 runs export profiles as null — no error (RunLog fields default None)
        "driver_profile": run_log.driver_profile,
        "vehicle_profile": run_log.vehicle_profile,
        # speed_profile and profile_overrides: None for pre-M5/pre-U5 runs (back-compat)
        "speed_profile": run_log.speed_profile,
        "profile_overrides": run_log.profile_overrides,
        "timeline_events": timeline_events,
        "decision_trace": decision_trace,
        "proposal_events": proposal_events,
        "actions": actions,
        "algorithm_errors": alg_errors,
    }

    # final_parameters: only when different from initial (setup change)
    if run_log.current_parameters != run_log.initial_parameters:
        simulator_facts["final_parameters"] = run_log.current_parameters

    # final_hyperparameters: only when different from initial
    if run_log.current_hyperparameters != run_log.initial_hyperparameters:
        simulator_facts["final_hyperparameters"] = run_log.current_hyperparameters

    # expert_override_events: V1 — not used; omit section entirely
    # run_comparison_reference: V1 — not used; omit section entirely

    # ── human_review (ONLY place feedback values appear) ──────────────────────
    feedback_labels = [
        {
            "target": e.target.model_dump(mode="json"),
            "labels": e.labels,
        }
        for e in feedback_events
    ]

    free_text_comments = [
        {
            "target": e.target.model_dump(mode="json"),
            "comment": e.comment,
        }
        for e in feedback_events
        if e.comment is not None
    ]

    human_review: dict[str, Any] = {
        "feedback_labels": feedback_labels,
        "free_text_comments": free_text_comments,
    }

    # ── Assemble final report ─────────────────────────────────────────────────
    return {
        "report_id": report_id,
        "run_id": run_log.run_id,
        "timestamp": timestamp,
        "ui_language": ui_language,
        "simulator_version": run_log.simulator_version,
        "package": {
            "id": run_log.snapshot.package.id,
            "version": run_log.snapshot.package.version,
        },
        "scenario": {
            "id": run_log.snapshot.scenario.id,
            "version": run_log.snapshot.scenario.version,
        },
        "simulator_facts": simulator_facts,
        "human_review": human_review,
    }
