"""Read-only preset store (feature 018 — Proposal Preset Test-Cases).

Scans a presets directory (``proposal_contracts/presets/`` in production)
for committed ``Preset`` JSON files. Mirrors the scan-a-directory structure
of ``WorldSeedStore`` (``services/world_seed_store.py``) — but, UNLIKE that
store (and ``DatasetCatalogRegistry``), which quarantine invalid files into
a ``list_errors()`` side-channel and keep serving the valid remainder, a
malformed preset here must be surfaced VISIBLY rather than silently skipped
(data-model.md §Preset: "Malformed/invalid preset ⇒ load rejected with a
visible error, never silently skipped into a degraded proposal";
contracts/preset_endpoints.md: "an invalid preset directory fails loudly at
startup/first-access"). ``_scan`` therefore RAISES ``PresetLoadError`` on the
first invalid file instead of collecting it.

Presets are COMMITTED, read-only artifacts generated by
``scripts/generate_presets.py`` (golden-pinned) — this store only reads
``*.json`` files under the presets directory (``README.md`` is skipped by
the glob) and never writes/mutates them.

Isolation (HARD ISOLATION RULE / CLAUDE.md): this module imports only
``aica_api.models.proposal.*``, ``aica_api.storage.file_store``, and
stdlib — never the trigger ``aica_api.models`` package, and never ``mdg``.

Public API:
  PresetStore(presets_dir: Path)
    .list_summaries()  -> list[PresetSummary]  — sorted by preset_id
    .get(preset_id)    -> Preset | None
"""
from __future__ import annotations

import pathlib

from aica_api.models.proposal.preset import Preset, PresetSummary
from aica_api.storage.file_store import read_json

__all__ = ["PresetLoadError", "PresetStore"]


class PresetLoadError(Exception):
    """Raised when a committed preset file fails to parse/validate, or its
    filename stem doesn't match its own ``preset_id`` (data-model.md
    validation rule: "preset_id ... matches filename stem"). Never
    quarantined — this is a load-time integrity error the caller must see.
    """


class PresetStore:
    """Read-only, in-memory index of committed preset test-cases."""

    def __init__(self, presets_dir: pathlib.Path) -> None:
        self._presets: dict[str, Preset] = {}
        self._scan(presets_dir)

    # ── Public API ─────────────────────────────────────────────────────────

    def list_summaries(self) -> list[PresetSummary]:
        """Return a PresetSummary projection for every preset, sorted by preset_id."""
        return [
            PresetSummary(
                preset_id=preset.preset_id,
                label=preset.label,
                brief=preset.brief,
                category=preset.category,
                family=preset.family,
                journey=preset.journey,
                contrast_with=preset.contrast_with,
                hypothesis=preset.expectation.hypothesis,
            )
            for preset in sorted(self._presets.values(), key=lambda p: p.preset_id)
        ]

    def get(self, preset_id: str) -> Preset | None:
        """Return the full, complete Preset for preset_id, or None if unknown."""
        return self._presets.get(preset_id)

    # ── Private helpers ────────────────────────────────────────────────────

    def _scan(self, presets_dir: pathlib.Path) -> None:
        """Scan presets_dir for ``*.json`` preset files.

        Raises:
            PresetLoadError: The FIRST file that fails to parse/validate, or
                whose ``preset_id`` doesn't match its filename stem — never
                partially exposes a directory containing an invalid preset.
        """
        if not presets_dir.exists():
            return

        for path in sorted(presets_dir.glob("*.json")):
            try:
                data = read_json(str(path))
                preset = Preset.model_validate(data)
            except Exception as exc:
                raise PresetLoadError(f"{path.name}: {exc}") from exc

            if path.stem != preset.preset_id:
                raise PresetLoadError(
                    f"{path.name}: preset_id {preset.preset_id!r} does not match "
                    f"filename stem {path.stem!r}"
                )

            self._presets[preset.preset_id] = preset
