"""Preset models (feature 018 — Proposal Preset Test-Cases).

A ``Preset`` is a committed, read-only test-case artifact: one file per
preset under ``proposal_contracts/presets/preset-<slug>.json``
(``services/preset_store.py`` scans/validates them; generated by
``scripts/generate_presets.py``, never hand-edited). It binds a full
``World`` + a bilingual brief/label + a machine-checkable ``expectation``
contract + optional per-selector ``algorithm_config_overrides`` into one
selectable unit (data-model.md §Preset, contracts/p1_preset.schema.json).

``PresetSummary`` is the lightweight list projection returned by
``GET /api/proposal/presets`` (data-model.md §PresetSummary) — avoids
shipping the full embedded ``World`` for every preset in a listing.

Isolation (HARD ISOLATION RULE / CLAUDE.md): this module imports only
``aica_api.models.proposal.*`` and pydantic/stdlib — never the trigger
``aica_api.models`` package, and never ``mdg``.
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from aica_api.models.proposal.enums import ServiceId
from aica_api.models.proposal.package_manifest import BilingualLabel
from aica_api.models.proposal.world import World

__all__ = [
    "PresetFamily",
    "PresetCategory",
    "PresetJourney",
    "ArousalBand",
    "Gradient",
    "ExpectedTop",
    "ExpectedServiceSet",
    "ExpectationContract",
    "AlgorithmConfigOverrides",
    "Preset",
    "PresetSummary",
]

# Fine-grained family tag (kept for continuity); "journey" tags a preset that is
# one step of a multi-stage journey timeline.
PresetFamily = Literal[
    "mood_coherence",
    "driver_state",
    "oshi_personalization",
    "genre_usage",
    "route_genre",
    "era_age",
    "passenger_genre",
    "singability_service",
    "history_mechanics",
    "baseline",
    "combo",
    "journey",
]

# Top-level grouping shown in the preset picker — the three content-scoring
# categories plus the baseline control.
PresetCategory = Literal["situation", "preference", "history", "baseline"]

ArousalBand = Literal["high", "mid", "low"]

Gradient = Literal["arousal_up_implies_fit_up", "arousal_down_implies_fit_up", "none"]


class ExpectedTop(BaseModel):
    """A predicate on the top candidate (data-model.md §ExpectationContract).

    The JSON schema's ``anyOf`` ("at least one field set") is a documented
    authoring rule for the generator, not re-enforced here — a stray
    all-``None``/``False`` ``ExpectedTop`` is a toothless-but-harmless
    predicate, never a data-integrity error worth rejecting a whole preset
    over.
    """

    model_config = ConfigDict(extra="forbid")

    track_id: str | None = None
    genre: str | None = None
    arousal_band: ArousalBand | None = None
    must_be_oshi: bool = False


class ExpectedServiceSet(BaseModel):
    model_config = ConfigDict(extra="forbid")

    top_should_be_in: list[ServiceId] = Field(min_length=1)


class ExpectationContract(BaseModel):
    """The documented claim the verification harness asserts against the
    real algorithm outputs (data-model.md §ExpectationContract)."""

    model_config = ConfigDict(extra="forbid")

    hypothesis: str = Field(min_length=1)
    expected_top: ExpectedTop
    top_fit_min: float = Field(ge=-1, le=1)
    gradient: Gradient
    should_rank_below: list[ExpectedTop] = []
    expected_service: ExpectedServiceSet
    override_required: bool


class AlgorithmConfigOverrides(BaseModel):
    """Isolated per-preset config deltas merged over the package defaults at
    dispatch time (data-model.md §AlgorithmConfigOverrides,
    ``services/algorithm_config.py::merge_algorithm_config``). Null/empty
    sub-fields mean "no override for this selector" — never mutates the
    package's own ``package.json``.
    """

    model_config = ConfigDict(extra="forbid")

    content: dict | None = None
    service: dict | None = None


class PresetJourney(BaseModel):
    """Timeline linkage — presets sharing a journey ``id`` form an ordered,
    same-driver sequence of driving stages (e.g. drive → rest → resume)."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(pattern=r"^[a-z0-9-]+$")
    step: int = Field(ge=1)
    of: int = Field(ge=1)
    label: BilingualLabel


class Preset(BaseModel):
    """The committed, read-only test-case artifact (data-model.md §Preset).

    ``world`` is the full ``World`` (control_inputs + situation +
    driver_profile + catalog_ref) — reused verbatim from
    ``models/proposal/world.py`` (never redefined here), matching the shape
    actually embedded in the committed ``preset-*.json`` files (NOT the
    ``SeedWorld`` wrapper, which additionally carries its own
    ``seed_id``/``label``/``description``).
    """

    model_config = ConfigDict(extra="forbid")

    preset_id: str = Field(pattern=r"^preset-[a-z0-9-]+$")
    schema_version: Literal["1.0.0"]
    label: BilingualLabel
    brief: BilingualLabel
    category: PresetCategory
    family: PresetFamily
    journey: "PresetJourney | None" = None
    contrast_with: str | None = Field(default=None, pattern=r"^preset-[a-z0-9-]+$")
    world: World
    algorithm_config_overrides: AlgorithmConfigOverrides | None = None
    expectation: ExpectationContract


class PresetSummary(BaseModel):
    """List projection for ``GET /api/proposal/presets`` (data-model.md
    §PresetSummary) — omits the embedded ``World`` to keep the listing light.
    Carries ``category``/``journey`` so the picker can group and order presets.
    """

    model_config = ConfigDict(extra="forbid")

    preset_id: str
    label: BilingualLabel
    brief: BilingualLabel
    category: PresetCategory
    family: PresetFamily
    journey: PresetJourney | None = None
    contrast_with: str | None = None
    hypothesis: str
