"""AICA API runtime configuration.

Resolves file-system paths for the six data directories:
  packages_dir              — AICA_PACKAGES_DIR                  (default: <repo-root>/packages)
  scenarios_dir             — AICA_SCENARIOS_DIR                 (default: <repo-root>/scenarios)
  runs_dir                  — AICA_RUNS_DIR                      (default: <repo-root>/runs)
  merged_runs_dir           — AICA_MERGED_RUNS_DIR               (default: <repo-root>/merged_runs)
  proposal_contracts_dir    — AICA_PROPOSAL_CONTRACTS_DIR        (default: <repo-root>/proposal_contracts)
  generation_workspace_dir  — AICA_GENERATION_WORKSPACE_DIR      (default: <repo-root>/generation_workspace)
  proposal_dataset_dir      — AICA_PROPOSAL_DATASET_DIR          (default: <repo-root>/proposal_contracts/dataset)
  proposal_runs_dir         — AICA_PROPOSAL_RUNS_DIR             (default: <repo-root>/proposal_runs)

The repo root is derived from this file's location:
  app/api/aica_api/config.py  →  parents[3]  →  repo root
Environment variable overrides always win. No third-party libraries are used.
"""

import os
from pathlib import Path

def _repo_root() -> Path:
    """Best-effort repo root for the default data-dir locations.

    Host layout: ``<repo>/app/api/aica_api/config.py`` → ``parents[3]`` = repo root.
    In the container the package is mounted at ``/app`` (a shallower path), where
    the default is never used because ``AICA_*_DIR`` env vars are set explicitly;
    guard the index so importing this module never raises there.
    """
    parents = Path(__file__).resolve().parents
    return parents[3] if len(parents) > 3 else parents[-1]


def _resolve(env_var: str, default_name: str) -> Path:
    """Return the Path from the env-var override, or the repo-root default."""
    override = os.environ.get(env_var)
    if override:
        return Path(override).resolve()
    return _repo_root() / default_name


class Settings:
    """Lightweight settings object — no Pydantic dependency."""

    @property
    def packages_dir(self) -> Path:
        return _resolve("AICA_PACKAGES_DIR", "packages")

    @property
    def scenarios_dir(self) -> Path:
        return _resolve("AICA_SCENARIOS_DIR", "scenarios")

    @property
    def runs_dir(self) -> Path:
        return _resolve("AICA_RUNS_DIR", "runs")

    @property
    def merged_runs_dir(self) -> Path:
        # Feature 020 (Combined Simulator) merged-run handles — a namespace
        # separate from both the trigger runs_dir and proposal_runs_dir.
        return _resolve("AICA_MERGED_RUNS_DIR", "merged_runs")

    @property
    def routes_dir(self) -> Path:
        return _resolve("AICA_ROUTES_DIR", "routes")

    @property
    def proposal_contracts_dir(self) -> Path:
        return _resolve("AICA_PROPOSAL_CONTRACTS_DIR", "proposal_contracts")

    @property
    def generation_workspace_dir(self) -> Path:
        return _resolve("AICA_GENERATION_WORKSPACE_DIR", "generation_workspace")

    @property
    def proposal_dataset_dir(self) -> Path:
        return _resolve("AICA_PROPOSAL_DATASET_DIR", "proposal_contracts/dataset")

    @property
    def proposal_runs_dir(self) -> Path:
        return _resolve("AICA_PROPOSAL_RUNS_DIR", "proposal_runs")

    @property
    def proposal_profiles_dir(self) -> Path:
        # User-saved driver profiles (P3). Built-in profiles ship under
        # proposal_contracts/; user profiles persist here (git-ignored).
        return _resolve("AICA_PROPOSAL_PROFILES_DIR", "proposal_profiles")

    @property
    def proposal_worlds_dir(self) -> Path:
        # User-created world clones (P3), git-ignored local artifacts.
        return _resolve("AICA_PROPOSAL_WORLDS_DIR", "proposal_worlds")

    @property
    def proposal_seeds_dir(self) -> Path:
        # Committed base-seed worlds (P3) promoted from the generator workspace.
        return _resolve("AICA_PROPOSAL_SEEDS_DIR", "proposal_contracts/seeds")

    @property
    def proposal_presets_dir(self) -> Path:
        # Committed preset test-cases (feature 018) generated by
        # scripts/generate_presets.py — golden-pinned, read-only.
        return _resolve("AICA_PROPOSAL_PRESETS_DIR", "proposal_contracts/presets")

    # ── LLM rationale (feature 019) — local Ollama server the backend calls ──
    # over HTTP (stdlib urllib, no new dependency). These are plain env-var
    # string/number settings (not filesystem paths), so they read os.environ
    # directly rather than via _resolve. The backend model path is OPT-IN: when
    # Ollama is unreachable the explain endpoint falls back to the deterministic
    # template, so these defaults are safe even when no Ollama is running.
    @property
    def ollama_base_url(self) -> str:
        return os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")

    @property
    def ollama_model(self) -> str:
        return os.environ.get("OLLAMA_MODEL", "qwen2.5:3b")

    @property
    def ollama_timeout_sec(self) -> float:
        return float(os.environ.get("OLLAMA_TIMEOUT_SEC", "20"))


settings = Settings()
