#!/usr/bin/env python3
"""Generate the human-readable preset analysis report (feature 018).

Runs the real content + service selectors on every committed preset and writes
the expected · REAL measured outcome · pass/fail to
``docs/master/proposal_preset_analysis.md`` (spec FR-016 / SC-007).

The report is organized the way the presets are meant to be READ:

  1. **Journeys** — one same-driver timeline per journey (A–F), stages in order,
     so you can follow what the assistant proposes as the drive evolves
     (fresh → drowsy → rest recommended → refreshed after the break).
  2. **Standalone presets** — grouped by category (situation / preference /
     history / baseline), each isolating one lever.
  3. **Contrast pairs** — presets whose #1 track must differ.

    cd app/api && uv run python ../../scripts/preset_analysis_report.py
"""
from __future__ import annotations

import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
if str(_REPO / "scripts") not in sys.path:
    sys.path.insert(0, str(_REPO / "scripts"))

import preset_eval as PE  # noqa: E402

_OUT = _REPO / "docs" / "master" / "proposal_preset_analysis.md"

_CATEGORY_ORDER = ["situation", "preference", "history", "baseline"]
_CATEGORY_TITLE = {
    "situation": "Situation — the drive decides",
    "preference": "Preference — the driver’s taste",
    "history": "History — past behavior",
    "baseline": "Baseline / control",
}


def _en(value) -> str:
    """English side of a bilingual `{ja,en}` label (or the value verbatim)."""
    if isinstance(value, dict):
        return value.get("en") or value.get("ja") or ""
    return str(value)


def _stage_title(label_en: str) -> str:
    """`"A · 1/4 — Cruising, Still Fresh"` -> `"Cruising, Still Fresh"`."""
    return label_en.split("—", 1)[1].strip() if "—" in label_en else label_en


def _expected_str(preset: dict) -> str:
    et = preset["expectation"].get("expected_top") or {}
    parts = []
    if et.get("must_be_oshi") is True:
        parts.append("oshi track")
    if et.get("must_be_oshi") is False:
        parts.append("NOT the oshi")
    if et.get("genre"):
        parts.append(f"genre={et['genre']}")
    if et.get("arousal_band"):
        parts.append(f"arousal={et['arousal_band']}")
    if et.get("track_id"):
        parts.append(f"track={et['track_id']}")
    parts.append(f"fit≥{preset['expectation']['top_fit_min']}")
    return ", ".join(parts)


def _verdict(r: dict) -> str:
    return "✅ pass" if r["ok"] else "❌ " + "; ".join(r["fails"])


def _real(r: dict) -> str:
    return f"{r['top_name']} ({r['top_fit']:+.3f} / a={r['arousal']:.2f})"


def _situation(preset: dict) -> str:
    ci = preset["world"]["control_inputs"]
    return f"{ci['trigger_purpose']} · {ci['lifecycle_stage']}"


def main() -> Path:
    presets = PE.load_presets()
    results = PE.evaluate_all()
    npass = sum(1 for r in results.values() if r["ok"])

    # Partition into journeys (by journey.id) and standalones (by category).
    journeys: dict[str, list[str]] = {}
    standalone: dict[str, list[str]] = {c: [] for c in _CATEGORY_ORDER}
    for pid, p in presets.items():
        j = p.get("journey")
        if j:
            journeys.setdefault(j["id"], []).append(pid)
        else:
            standalone.setdefault(p.get("category") or "baseline", []).append(pid)

    L: list[str] = []
    L.append("# Proposal preset analysis — expected vs. real outcome\n")
    L.append("> Generated by `scripts/preset_analysis_report.py` from the REAL content + "
             "service selectors over the frozen catalog. Do not hand-edit.\n")
    L.append(f"**{npass}/{len(results)} presets pass their expectation contract** "
             f"({len(journeys)} journeys · "
             f"{sum(len(v) for v in standalone.values())} standalone).\n")
    L.append("Global retune in effect: `content_category_weights = {Situation 0.45, "
             "Preference 0.35, History 0.20}` (was 0.55/0.30/0.15). The `norm_bounds` "
             "loudness recalibration was evaluated and **rejected** — measured effect on "
             "scores was negligible (≤0.005), so the frozen bounds are unchanged.\n")

    L.append("## How to read this\n")
    L.append("A content **fit** is a signed weighted average of ~15 features that sum to 1, "
             "so it lives in a narrow band by construction: a cold-start driver tops out near "
             "**0.10–0.20** (much of the weight — oshi / age / play / recovery history — has "
             "nothing to act on, and by design that missing weight is never redistributed), "
             "while a driver with an in-catalog oshi + real history legitimately reaches "
             "**0.37–0.44**. Low is not broken — it is an honest cold start.\n")
    L.append("Drowsiness/fatigue/monotony in each brief are grounded in the trigger-mode "
             "driver-signal model, so the journeys track a physically plausible arc: "
             "drowsiness outpaces fatigue, a real break (sleep/karaoke/stretch) knocks it "
             "back down, and the proposal shifts from **energize** (fight the boredom) to "
             "**soothe** (wind down) accordingly.\n")

    # ---- Journeys (timelines) ---------------------------------------------
    L.append("## Journeys — same driver, staged over one drive\n")
    for jid in sorted(journeys):
        stages = sorted(journeys[jid], key=lambda pid: presets[pid]["journey"]["step"])
        head = presets[stages[0]]
        j = head["journey"]
        L.append(f"### {_en(j['label'])}\n")
        L.append("| # | Stage | Situation (purpose · lifecycle) | Real top (fit / arousal) | "
                 "Service | Result |")
        L.append("|---|---|---|---|---|---|")
        for pid in stages:
            p, r = presets[pid], results[pid]
            L.append(f"| {p['journey']['step']}/{p['journey']['of']} "
                     f"| {_stage_title(_en(p['label']))} | {_situation(p)} "
                     f"| {_real(r)} | {r['service_top']} | {_verdict(r)} |")
        L.append("")  # blank line after table

    # ---- Standalone presets by category -----------------------------------
    L.append("## Standalone presets — one lever each\n")
    for cat in _CATEGORY_ORDER:
        pids = sorted(standalone.get(cat, []))
        if not pids:
            continue
        L.append(f"### {_CATEGORY_TITLE[cat]}\n")
        L.append("| Preset | Family | Hypothesis | Expected | Real top (fit / arousal) | "
                 "Service | Override | Result |")
        L.append("|" + "|".join(["---"] * 8) + "|")
        for pid in pids:
            p, r = presets[pid], results[pid]
            ov = "yes" if p["expectation"].get("override_required") else "—"
            L.append(f"| `{pid}` | {p['family']} | {p['expectation']['hypothesis']} "
                     f"| {_expected_str(p)} | {_real(r)} | {r['service_top']} | {ov} "
                     f"| {_verdict(r)} |")
        L.append("")

    # ---- Contrast pairs ----------------------------------------------------
    L.append("## Contrast pairs — the #1 track must differ\n")
    seen: set = set()
    L.append("| A | B | A top | B top | Diverge |")
    L.append("|---|---|---|---|---|")
    for pid, p in presets.items():
        cw = p.get("contrast_with")
        if cw and (pid, cw) not in seen and (cw, pid) not in seen:
            seen.add((pid, cw))
            a, b = results[pid]["top"], results[cw]["top"]
            L.append(f"| `{pid}` | `{cw}` | {results[pid]['top_name']} | "
                     f"{results[cw]['top_name']} | {'✅' if a != b else '❌ SAME'} |")

    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text("\n".join(x for x in L if x is not None) + "\n", encoding="utf-8")
    return _OUT


if __name__ == "__main__":
    out = main()
    print(f"wrote {out}")
